name: "nix-flake-debian-home-manager"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/362477fdf726ed1dff33eadda8b99b257b46e085.tar.gz
        fetch-depth: 0
        submodules: true

    - run: touch dotfiles/keys.sh
    - run: nix-shell -p home-manager --command 'home-manager -f home.nix -n instantiate'
