name: "nix-flake-debian-home-manager"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        fetch-depth: 0
        submodules: true

    - run: nix-shell -p home-manager --command 'home-manager -f home.nix -n instantiate'
